version: 2.1.1.{build}
environment:
  my_version: 2.1.1
  my_secret:
    secure: cKtBgJPiEZHUw2elDOU8OA==
skip_branch_with_pr: true
image: Visual Studio 2017
clone_folder: c:\projects\ILRepack.Lib.MSBuild
platform: Any CPU
configuration: Release
install:
- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
- cmd: appveyor-tools\secure-file -decrypt "c:\projects\ILRepack.Lib.MSBuild\ILRepack.Lib.MSBuild\ILRepack.Lib.MSBuild.snk.enc" -secret %my_secret%

before_build:
- cmd: nuget restore

after_build:
- nuget pack "c:\projects\ILRepack.Lib.MSBuild\ILRepack.Lib.MSBuild\build\ILRepack.Lib.MSBuild.nuspec"

artifacts:
- path: ILRepack.Lib.MSBuild.%my_version%.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: f061iyHEh8+Fz3+iV/c+3stBhQuyndcJMP719Eny9w6sbRfMgD1yJe+aVAYW1PJD
  skip_symbols: false
  artifact: ILRepack.Lib.MSBuild.%my_version%.nupkg
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only